### ISSUE TITLE
Consults window

### ISSUE THREAD

**Issue by sic-f** [sic-f/lasp#2]
### Components:
* #### Header
    a) Label - patient's full name
    b) Button to create a new consult

* #### Table
   Fields:
        a) PIN (value field)
        b) Hospital (dropdown)
        c) Date of consult (value field)
        d) Account (dropdown)
        e) Summary of consult (text field)
        d) Other findings (text field)

#### Tasks:
- [x] Window size of tabbed window
- [x] Create a consult and with its associated objects
- [x] Delete consult
- [x] Show and update consult

**Comment by sic-f** [comment]
- [ ] Window size of tabbed window
